apiVersion: v2
name: excalibase-graphql
description: Automatic GraphQL API generation from multiple databases
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - graphql
  - postgresql
  - mysql
  - api
home: https://github.com/excalibase/excalibase-graphql
sources:
  - https://github.com/excalibase/excalibase-graphql
maintainers:
  - name: Excalibase Team
    url: https://github.com/excalibase
