{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "excalibase-graphql.fullname" . }}
  labels:
    {{- include "excalibase-graphql.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
  {{- if .Values.app.security.multiTenant.provisioningPat }}
  provisioning-pat: {{ .Values.app.security.multiTenant.provisioningPat | quote }}
  {{- end }}
{{- end }}
