server:
  port: 10000
spring:
  application:
    name: Excalibase graphql
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hana
    username: hana001
    password: password123
    hikari:
      schema: hana
app:
  allowed-schema: public
  database-type: postgres
logging:
  level:
    root: ${log.level.root:info}
    org:
      springframework: ${log.level.spring:info}
    io:
      github:
        excalibase: ${log.level.app:info}
  pattern:
    console: "%d{ISO8601} %highlight(%-5level) [%blue(%t)] [%blue(%X{remoteAddr})] %yellow(%C{1}): %msg%n%throwable"